### ISSUE TITLE
Incorrect information in python_tutorial.ipynb

### ISSUE THREAD

**Issue by agarwalrounak** [Cantera/cantera-jupyter#24]
After setting `gas1.TP = 1200, 101325` and calling `gas1()` it is mentioned that `the temperature has been changed as requested, but the pressure has changed too. The density and the composition have not.` This is wrong because the pressure is the same. It is the density that has changed. 

Once the issue is approved, I can start working on it.

**Comment by agarwalrounak** [comment]
@bryanwweber Do you think this issue is valid? Please let me know so that I can send a fix for it.

**Comment by bryanwweber** [comment]
Sure, seems like a simple typo fix.
