### ISSUE TITLE
Figures don't render correctly on GitHub on some browsers

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera-jupyter#37]
SVG figures are not properly displayed on at least some browsers (both Chrome and Firefox on FC35) ... see https://github.com/Cantera/cantera-jupyter/blob/main/electrochemistry/lithium_ion_battery.ipynb (text is not rendered)
![Screenshot from 2022-04-05 11-15-58](https://user-images.githubusercontent.com/12603999/161799408-913c4127-68ab-487d-b9e9-3e1242117b71.png)

*Edit: change was introduced in #34*

**Comment by bryanwweber** [comment]
Well that's disappointing... I can reproduce this on my Mac in Chrome as well.

**Comment by decaluwe** [comment]
So is the solution just to change the line 
> %config InlineBackend.figure_formats = ["svg"]

to something like:
> %config InlineBackend.figure_formats = ["png"]

?

**Comment by decaluwe** [comment]
(also, fwiw, it goes beyond text not being rendered - there is a whole plot element (red circles that overlap with the blue trace) that is not plotted.

Thanks for catching this, @ischoegl

**Comment by speth** [comment]
Is the concern just how these are rendered by GitHub? I think that's always had some issues, so if the figures look OK when viewed (a) in Jupyter and (b) when rendered as HTML for the Cantera website, I don't think there's that much of an issue here.

I tried (a) and (b) on my Mac with both Safari and Firefox, and they look fine.

**Comment by speth** [comment]
It seems like this has been resolved on GitHub's end -- the plots in the linked example look just fine to me.
