### ISSUE TITLE
cantera-jupyter/thermo /flame_temperature.ipynb

### ISSUE THREAD

**Issue by rddaz2013** [Cantera/cantera-jupyter#44]
Hello,

the 'old' Example with the Flame Temperature has an Attribute Error with Cantera version: 3.0.0.

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[2], line 2
>       1 # Get all of the Species objects defined in the GRI 3.0 mechanism
> ----> 2 species = {S.name: S for S in ct.Species.listFromFile("gri30.yaml")}
>       4 # Create an IdealGas object with species representing complete combustion
>       5 complete_species = [species[S] for S in ("CH4", "O2", "N2", "CO2", "H2O")]
> 
> AttributeError: type object 'cantera.thermo.Species' has no attribute 'listFromFile'

**Comment by speth** [comment]
This is resolved in the latest version of the example, now part of the "User Guide" at https://cantera.org/3.1/userguide/flame-temperature.html.
